// Post-generation enrichment for AI-generated practice questions.
//
// Two guarantees per question:
//   1. COVERAGE — if a graph would meaningfully help and one is missing, add it.
//   2. MATH CORRECTNESS — every `line`-type graph has values computed by Node
//      (Math.* eval), not LLM arithmetic. This catches the failure mode where
//      Sonnet writes "y = 2x³ – 3x²" and then lists numerically wrong y values.
//
// All AI judgment happens here (decide whether a graph helps, extract the
// function as a JS expression). Arithmetic happens in pure JS via `new Function`
// against a whitelisted Math.* subset. If anything fails — JSON parse, unsafe
// expression, domain errors — the question is returned untouched. Better to
// ship the original Q than a broken enriched one.

import { chatCompletion, type Usage } from "./claude";
import type { Question, GraphData } from "./types";

interface ExamMeta {
  subject: string;
  level: number;
  standard?: string;
}

interface SeriesExpression {
  name: string;
  expr: string;
}

interface EnrichmentDecision {
  keep_existing?: boolean;
  set_graph?: GraphData;
  series_exprs?: SeriesExpression[];
  reason?: string;
}

// Hard whitelist for JS math expressions. Anything else is rejected.
function buildEvaluator(expr: string): (x: number) => number {
  // Strip every legitimate token; whatever remains is suspicious. We use a
  // global `x` strip (NOT word-bounded) because `x**2` collapses to `xx` after
  // operators are removed and a word-bounded \bx\b would refuse to match.
  const stripped = expr
    .replace(/Math\.(sin|cos|tan|asin|acos|atan|atan2|exp|log|log2|log10|sqrt|cbrt|abs|pow|sign|floor|ceil|round|min|max|PI|E|LN2|LN10|LOG2E|LOG10E|SQRT2)/g, "")
    .replace(/[0-9.eE+\-*/(),%\s]/g, "")
    .replace(/x/g, "");
  if (stripped.length > 0) {
    throw new Error(`unsafe tokens "${stripped}" in expression "${expr}"`);
  }
   
  return new Function("x", `"use strict"; return (${expr});`) as (x: number) => number;
}

function safeEvalAt(expr: string, xs: number[]): { xs: number[]; values: number[] } | null {
  let fn: (x: number) => number;
  try { fn = buildEvaluator(expr); } catch { return null; }
  const cleanXs: number[] = [];
  const cleanVs: number[] = [];
  for (const x of xs) {
    try {
      const y = fn(x);
      if (Number.isFinite(y)) {
        cleanXs.push(x);
        cleanVs.push(Math.round(y * 10000) / 10000);
      }
    } catch {
      // domain error at this x — skip the point
    }
  }
  if (cleanXs.length < 3) return null;
  return { xs: cleanXs, values: cleanVs };
}

const ENRICHER_SCHEMA = `Output ONLY valid JSON, no markdown. One of:

A) Keep the question's graph as-is (or keep it with no graph):
   {"keep_existing": true, "reason": "<short>"}

B) Replace / set the graph. Use this for new graphs, fixed graphs, or recomputed graphs:
   {
     "set_graph": <GraphData object>,
     "series_exprs": [   // REQUIRED if set_graph.type === "line", omit otherwise
       {"name": "<series name matching one in set_graph>", "expr": "<JS expression in x>"}
     ],
     "reason": "<short>"
   }

GraphData TypeScript shape:
{
  type: "bar" | "line" | "pie" | "scatter" | "box-plot" | "histogram" | "table" | "number-line",
  title?: string, xLabel?: string, yLabel?: string,
  data?: ...,            // for bar/pie/scatter/box-plot/histogram/table/number-line
  xValues?: number[],    // for line
  series?: [{name, values: number[]}, ...]  // for line
}

By type:
bar       data = [{label, value}, ...]
line      xValues = [...], series = [{name, values: [...]}, ...]
          (values get replaced by Math eval of the matching series_expr — use placeholder zeros)
pie       data = [{label, value}, ...]
scatter   data = [[x,y], ...]
box-plot  data = [{label, value}, ...] EXACTLY 5 in order min/Q1/median/Q3/max
histogram data = [{label, value}, ...]
table     data = {headers: [...], rows: [[...], ...]}
number-line  xValues = [leftEnd, rightEnd], data = [{label, value}, ...]

JavaScript expression rules (for series_exprs):
- Only Math.* (Math.sin, Math.cos, Math.tan, Math.exp, Math.log, Math.sqrt, Math.abs, Math.pow, Math.PI, Math.E)
- Use ** for exponentiation (always parenthesise negative bases: (-x)**2)
- Use x as the variable
Examples:
- "y = 2x³ – 3x² + 5"        → "2 * x**3 - 3 * x**2 + 5"
- "y = e^(-x/2)"             → "Math.exp(-x / 2)"
- "Demand: P = 100 - 5Q"     → "100 - 5 * x"
- "Supply: P = 10 + 2Q"      → "10 + 2 * x"`;

function buildEnrichPrompt(q: Question, meta: ExamMeta): string {
  return `You are auditing one NCEA practice exam question to guarantee its visual is correct and useful. This question was just generated by an LLM — values may be wrong, or a beneficial graph may be missing.

SUBJECT: ${meta.subject}  LEVEL: ${meta.level}${meta.standard ? `  STANDARD: ${meta.standard}` : ""}

QUESTION TEXT:
${q.text}

ANSWER TYPE: ${q.answerType}   MARKS: ${q.marks}

EXPECTED ANSWER:
${q.expectedAnswer ?? "(none)"}

MARKING GUIDE:
${q.markingGuide ?? "(none)"}

CURRENT GRAPH:
${q.graph ? JSON.stringify(q.graph, null, 2) : "(none)"}

YOUR JOB — decide one of:

★ HARD RULE — IF THE QUESTION TEXT CONTAINS A FUNCTION DEFINITION, YOU MUST SET A LINE GRAPH OF THAT FUNCTION. NO EXCEPTIONS.
   Patterns that trigger this (case-insensitive):
   • f(x) = …      • g(x) = …      • h(x) = …      • y = …
   • f(t) = …      • h(t) = …      • d(t) = …      • v(t) = …      • s(t) = …
   • P(x) = …      • C(x) = …      • R(x) = …      • Q(x) = …      • N(t) = …      • m(t) = …
   • any "y = ax² + bx + c", "y = ax³ + bx² + …", "exp(…)", "ln(…)", "log(…)", "sin(…)", "cos(…)"
   Even if the question asks only for a derivative, a single value, or a rate of change at one point — you STILL set a line graph of the underlying function. A function-defined question without a graph is unacceptable.
   When this rule fires: set_graph.type = "line", choose xValues spanning a sensible domain (≥10 points), supply series_exprs with the JS expression for that exact function.

★ MANDATORY: SET a graph (do NOT keep_existing) whenever ANY of these apply to the question:
   - Question describes a supply curve, demand curve, AS/AD, PPF, cost curve, isoquant, indifference curve → line graph with one series per curve.
   - Question gives a dataset of paired values (scatter), a five-number summary (box-plot), binned frequencies (histogram), or categorical comparisons of ≥2 items (bar).
   - Question references a table of structured data (financial statements, dates of events, observation tables, ≥2 rows × ≥2 cols) → table graph.
   - Question describes a time series, growth, decay, motion (d/v/a vs t), titration, energy profile, rate-vs-time, population-vs-time → line graph.

KEEP EXISTING only when:
   - Pure arithmetic with a one-line answer and no function involved (e.g. "calculate 12% of 850", "what is the pH of 0.1 M HCl?", word-problem unit conversions)
   - Pure explain / define / describe / discuss / essay with no quantitative model
   - Chemical balancing, naming, or structural-formula work (text-based)
   - English / history / classical-studies / art-history / te-reo / media-studies essay-style questions
   - There's ALREADY an existing non-line graph that's correct and faithful
   - The "graph" you'd add would be a single number, a 1×2 table, or otherwise so trivial it adds no value

ABSOLUTE RULES (return keep_existing instead if any apply):
- DO NOT give away the answer. Never plot the maximum point, the equilibrium point, the answer x-value, or any labelled solution data. The graph shows the FUNCTION/DATA from the question, never the solved answer.
- DO NOT use scatter/line/bar to draw shapes (circles, triangles, anatomical drawings, free-body diagrams, circuit diagrams, molecular structures, maps). Our renderer only does data charts.
- DO NOT ask the student to draw/sketch/plot.
- For line graphs of functions: MUST include series_exprs with one JS expression per series. The values you put in series[*].values will be DISCARDED — only your series_exprs are used to compute the actual y values. Be lazy about values (zeros fine) but BE CORRECT in the expr.
- For line graphs of functions: choose xValues that span a reasonable domain for the function (e.g. for a profit-maximisation P(x) = -50x² + 1200x - 4000 where the max is around x=12, pick xValues like [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24] — ≥10 points across a sensible range).

${ENRICHER_SCHEMA}

Take your time. Re-read the question. Pick the right decision.`;
}

function tryParse(text: string): EnrichmentDecision | null {
  const c = text.replace(/^```(?:json)?\s*/i, "").replace(/```\s*$/i, "").trim();
  const s = c.indexOf("{"), e = c.lastIndexOf("}");
  if (s < 0 || e <= s) return null;
  try { return JSON.parse(c.slice(s, e + 1)) as EnrichmentDecision; }
  catch { return null; }
}

// Apply series_exprs to a line graph: replace each series' values with JS-eval'd
// values, drop x-points where any series is undefined.
function recomputeLineGraph(graph: GraphData, exprs: SeriesExpression[]): GraphData | null {
  if (graph.type !== "line") return graph;
  const xs = graph.xValues;
  const series = graph.series;
  if (!Array.isArray(xs) || !Array.isArray(series) || series.length === 0) return null;
  // Build evaluators for each series. If we can't find/eval one, give up entirely.
  const evals: Array<(x: number) => number> = [];
  for (const s of series) {
    const match = exprs.find((e) => e.name === s.name);
    if (!match) return null;
    try { evals.push(buildEvaluator(match.expr)); }
    catch { return null; }
  }
  // Evaluate all series at each x. Keep only xs where ALL series are finite.
  const cleanXs: number[] = [];
  const newVals: number[][] = series.map(() => []);
  for (const x of xs) {
    const yArr: number[] = [];
    let allFinite = true;
    for (const fn of evals) {
      try {
        const y = fn(x);
        if (Number.isFinite(y)) yArr.push(Math.round(y * 10000) / 10000);
        else { allFinite = false; break; }
      } catch { allFinite = false; break; }
    }
    if (allFinite) {
      cleanXs.push(x);
      yArr.forEach((y, i) => newVals[i].push(y));
    }
  }
  if (cleanXs.length < 3) return null; // not enough points to render a curve
  return {
    ...graph,
    xValues: cleanXs,
    series: series.map((s, i) => ({ ...s, values: newVals[i] })),
  };
}

// Convert a math expression from question-text notation (using ² ³ etc., implicit
// multiplication, named variables) into a JS expression in x. Returns null if the
// expression is too ambiguous to parse safely.
function questionExprToJs(rhs: string, variable: string): string | null {
  // Strip whitespace and normalise unicode minus / multiplication
  let s = rhs.trim()
    .replace(/[–—−]/g, "-")
    .replace(/[×·]/g, "*")
    .replace(/[÷]/g, "/");
  // Replace superscript digits with **n. The 10 superscript digits are spread
  // across two Unicode blocks (U+00B2/B3 for ²/³, U+00B9 for ¹, U+2070 for ⁰,
  // U+2074–U+2079 for ⁴–⁹), so we list them explicitly rather than using a range.
  const SUP: Record<string, string> = {"⁰":"0","¹":"1","²":"2","³":"3","⁴":"4","⁵":"5","⁶":"6","⁷":"7","⁸":"8","⁹":"9"};
  s = s.replace(/([a-zA-Z0-9)\]])([⁰¹²³⁴⁵⁶⁷⁸⁹]+)/g, (_, base, sup) => `${base}**${sup.split("").map((c: string) => SUP[c] ?? "").join("")}`);
  // Replace "x²" / "t²" form with x**2 / t**2 (after the superscript pass, mostly belt-and-braces)
  // Replace "x^n" → "x**n"
  s = s.replace(/\^/g, "**");
  // Insert explicit * between digit and variable, between digit and (, between var and (, between ) and var, etc.
  // e.g. "45 + 8t - 0.5t**2" → "45 + 8*t - 0.5*t**2"
  const v = variable;
  const reDigVar = new RegExp(`(\\d|\\))\\s*(${v}|Math\\.|\\()`, "g");
  s = s.replace(reDigVar, "$1*$2");
  // Replace the variable letter with `x` so the evaluator always uses x
  if (v !== "x") {
    s = s.replace(new RegExp(`\\b${v}\\b`, "g"), "x");
  }
  // Common functions: ln→Math.log, log→Math.log10 (NCEA default), sin/cos/tan→Math.*, e^→Math.exp
  s = s.replace(/\bln\s*\(/g, "Math.log(");
  s = s.replace(/\blog\s*\(/g, "Math.log10(");
  s = s.replace(/\b(sin|cos|tan|asin|acos|atan|sqrt|exp|abs)\s*\(/g, "Math.$1(");
  s = s.replace(/\be\s*\*\*\s*\(/g, "Math.exp(");
  // Sanity: must contain x, must be evaluable
  if (!/\bx\b/.test(s) && !/^[\s\d.+\-*/()e]+$/.test(s)) return null;
  try {
    const fn = buildEvaluator(s);
    const probe = fn(1);
    if (!Number.isFinite(probe)) return null;
    return s;
  } catch {
    return null;
  }
}

// Regex-detect function definitions like "f(x) = …", "P(t) = …", "y = …" in
// the question text. Returns the matched function expression converted to JS.
// Used as a CODE-LEVEL fallback when the LLM enricher missed a function-based
// question.
function detectFunctionExpression(text: string): { jsExpr: string; varName: string; domainHint: { min: number; max: number } | null } | null {
  // Pattern A: f(x) = …   /   h(t) = …   /   P(x) = …
  // Pattern B: y = …
  // We grab the RHS up to the end of line, comma, or sentence-ending period
  // (period followed by whitespace or end-of-string — NOT periods inside
  // decimals like "0.5", which would otherwise truncate the expression early).
  // Capture up to comma, newline, sentence-ending period (period + whitespace
  // or end), or question mark. The `.` inside decimals like "0.5" stays in.
  const TERM = `(?=,|\\n|\\.\\s|\\.$|\\?|$)`;
  const A = new RegExp(`\\b([a-zA-Z])\\s*\\(\\s*([a-zA-Z])\\s*\\)\\s*=\\s*([^,\\n]+?)${TERM}`);
  const B = new RegExp(`\\by\\s*=\\s*([^,\\n]+?)${TERM}`);
  let rhs: string | null = null;
  let variable = "x";
  const mA = text.match(A);
  if (mA) {
    variable = mA[2];
    rhs = mA[3];
  } else {
    const mB = text.match(B);
    if (mB) {
      // We don't know the variable; default to x. The rhs may use x.
      rhs = mB[1];
      variable = "x";
    }
  }
  if (!rhs) return null;
  // Strip trailing "where ...", ", for ...", etc.
  rhs = rhs.replace(/\s+(where|for|when|with|if)\b.*$/i, "").trim();
  // Reject if RHS looks like a sentence (has more than 8 words) — probably not a formula.
  if (rhs.split(/\s+/).length > 12) return null;
  const jsExpr = questionExprToJs(rhs, variable);
  if (!jsExpr) return null;
  // Try to detect domain hints like "for 0 ≤ x ≤ 10"
  let domainHint: { min: number; max: number } | null = null;
  const domA = text.match(/for\s+(-?\d+\.?\d*)\s*[<≤]\s*[a-zA-Z]\s*[<≤]\s*(-?\d+\.?\d*)/i);
  if (domA) domainHint = { min: parseFloat(domA[1]), max: parseFloat(domA[2]) };
  return { jsExpr, varName: variable, domainHint };
}

function makeAutoLineGraph(text: string): GraphData | null {
  const detected = detectFunctionExpression(text);
  if (!detected) return null;
  const { jsExpr, varName, domainHint } = detected;
  // Pick xValues spanning the domain hint, or [-5, 10] by default. Always ≥13 points.
  const min = domainHint?.min ?? 0;
  const max = domainHint?.max ?? (domainHint ? 10 : 10);
  const span = max - min;
  if (span <= 0) return null;
  const step = span / 16;
  const xs: number[] = [];
  for (let i = 0; i <= 16; i++) xs.push(Math.round((min + i * step) * 1000) / 1000);
  const result = safeEvalAt(jsExpr, xs);
  if (!result) return null;
  return {
    type: "line",
    title: `y = ${detected.varName === "x" ? "f(x)" : `f(${detected.varName})`}`,
    xLabel: varName,
    yLabel: "y",
    xValues: result.xs,
    series: [{ name: "y", values: result.values }],
  };
}

// Public API: enrich a single question. Returns the question (modified or
// untouched) and the API usage. Never throws; on any failure, returns original.
//
// Priority order — designed to GUARANTEE math correctness:
//   1. If the question text contains a regex-detectable function (e.g.
//      "P(x) = -2x³ + 45x² + 300x - 5000"), build the graph from the regex +
//      Node eval. No LLM round-trip, math is provably correct. Covers the
//      common case for maths/physics/economics single-function questions.
//   2. Otherwise, ask the LLM whether a graph would help (tables, multi-series
//      supply/demand line graphs, scatter plots, distributions).
export async function enrichQuestionGraphs(
  q: Question,
  meta: ExamMeta,
): Promise<{ question: Question; usage?: Usage }> {
  // Step 1 — regex code path. Deterministic, math-guaranteed. Always wins
  // for single-function questions regardless of what the LLM might say.
  const auto = makeAutoLineGraph(q.text ?? "");
  if (auto) {
    return { question: { ...q, graph: auto } };
  }

  // If the question already has a graph from generation and we couldn't
  // auto-build a function curve, leave it alone (could be table, bar, etc.).
  if (q.graph) {
    return { question: q };
  }

  // Step 2 — LLM path for everything else (multi-series, tables, scatter).
  let result: { text: string; usage: Usage };
  try {
    result = await chatCompletion(buildEnrichPrompt(q, meta), { smart: true, maxTokens: 2000 });
  } catch {
    return { question: q };
  }
  const decision = tryParse(result.text);
  if (!decision || decision.keep_existing || !decision.set_graph || !decision.set_graph.type) {
    return { question: q, usage: result.usage };
  }

  let newGraph: GraphData | null = decision.set_graph;
  if (newGraph.type === "line") {
    const exprs = decision.series_exprs ?? [];
    if (exprs.length === 0) {
      // Line graph without exprs — can't math-verify, refuse.
      return { question: q, usage: result.usage };
    }
    newGraph = recomputeLineGraph(newGraph, exprs);
    if (!newGraph) return { question: q, usage: result.usage };
  }

  return { question: { ...q, graph: newGraph }, usage: result.usage };
}

// Enrich every question in a paper in parallel (bounded concurrency).
export async function enrichPaperGraphs(
  questions: Question[],
  meta: ExamMeta,
): Promise<{ questions: Question[]; usages: Usage[] }> {
  const out = await Promise.all(questions.map((q) => enrichQuestionGraphs(q, meta)));
  return {
    questions: out.map((r) => r.question),
    usages: out.map((r) => r.usage).filter((u): u is Usage => Boolean(u)),
  };
}
